FROM ubuntu
WORKDIR /app

RUN apt update && apt upgrade 
RUN apt install -y wget
RUN wget --no-check-certificate https://media.sundog-soft.com/es7/shakes-mapping.json

#RUN apt-get update
#RUN apt-get -y wget
#RUN wget --no-check-certificate https://media.sundog-soft.com/es7/shakes-mapping.json

CMD ["bash"]