version: '3'
services: 
  ubuntu:
    depends_on: 
      - elasticsearch
    build: 
      context: ./
      dockerfile: Dockerfile.ubuntu
    # command: /bin/bash -c "load-shakespeare.sh"
    stdin_open: true
    tty: true
    networks:
      - elastic
  elasticsearch:
    image: elasticsearch:7.6.0
    environment: 
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - elastic
networks: 
  elastic: